### PR TITLE
126 obsolete dropdown description

### PR DESCRIPTION
**Pull request by PatrykSzwer**
#126

### CODE REVIEW

File: src/KitchenSink/wwwroot/KitchenSink/DropdownPage.html [hunk 1]
```diff
@@ -17,19 +17,18 @@ <h1 slot="kitchensink/dropdown-header">Primitive array</h1>
         <p slot="kitchensink/dropdown-objects-header" class="lead">Objects array</p>
 
         <p slot="kitchensink/dropdown-objects-description" class="lead">A combination of object <code>array</code> and bound JSON string property can be mapped to an HTML <code>select</code> element.</p>
-
-        <small slot="kitchensink/dropdown-objects-value-description">Polymer applies <code>value</code> binding before options generated. That is why there is no value.</small>
-
+   
+        <small slot="kitchensink/dropdown-objects-select-description">The HTML <code>select</code> element can not contain a value which does not exists in it's options collection, because the <code>value</code> binding is executed before options are rendered by the dom-repeat.  This leads to the loss of the initial value.</small>
```
Comment (warpech) [inline src/KitchenSink/wwwroot/KitchenSink/DropdownPage.html]: I'd propose different explanation: 

```txt
<small slot="kitchensink/dropdown-objects-select-description">Polymer 1.x executes the <code>value</code> binding in the <code>select</code> element before evaluating <code>dom-repeat</code>. This makes it impossible to preselect an <code>option</code> element, which is illustrated below ("Starcounter Database" should be preselected).</small>
```

File: src/KitchenSink/wwwroot/KitchenSink/DropdownPage.html [hunk 2]
```diff
@@ -17,19 +17,18 @@ <h1 slot="kitchensink/dropdown-header">Primitive array</h1>
...
+        
         <select slot="kitchensink/dropdown-objects-select" class="kitchensink-select kitchensink-test-product-select" value="{{model.SelectedProductKey$::change}}">
-            <option></option>
             <template is="dom-repeat" items="{{model.Products}}">
                 <option value="{{item.Key}}">{{item.Name}}</option>
             </template>
         </select>
 
-        <small slot="kitchensink/dropdown-objects-juicy-select-description">You can use <code>juicy-select</code> to workaround issue with value binding.</small>
+        <small slot="kitchensink/dropdown-objects-juicy-select-description">You can use custom element <code>juicy-select</code> to workaround this issue.</small>
```
Comment (warpech) [inline src/KitchenSink/wwwroot/KitchenSink/DropdownPage.html]: `workaround this issue` -> `workaround the above issue`

File: src/KitchenSink/DropdownPage.json.cs [hunk 3]
```diff
@@ -39,25 +39,14 @@ protected override void OnData()
...
-            get
-            {
-                if (this.SelectedProduct == null)
-                {
-                    return null;
-                }
-
-                return this.SelectedProduct.Key;
-            }
+            get => SelectedProduct?.Key;
```
Comment (warpech) [inline src/KitchenSink/DropdownPage.json.cs]: For some reason, this fails on the build agent:

```
Open in IDE
DropdownPage.json.cs(49, 17): error CS1043: { or ; expected
DropdownPage.json.cs(49, 17): error CS1513: } expected
DropdownPage.json.cs(50, 16): error CS1002: ; expected
DropdownPage.json.cs(62, 2): error CS1513: } expected
```

See https://teamcity.starcounter.org/viewLog.html?buildId=24647&tab=buildResultsDiv&buildTypeId=Apps_KitchenSink_Develop

Is this some language feature that is not available in the build agent? I'd rather fix it in the build agent then.

Comment (warpech) [inline src/KitchenSink/DropdownPage.json.cs]: This one is used in the build agent:

MSBuild version: Microsoft Build Tools 2015
MSBuild ToolsVersion: 14.0

Comment (warpech) [inline src/KitchenSink/DropdownPage.json.cs]: I will check if that works with 2017 / 15.0

Comment (PatrykSzwer) [inline src/KitchenSink/DropdownPage.json.cs]: Sorry, Didn't noticed that it failed.
That's pretty strange, It's just simple expression body with null-conditional (c# 6.0 features). Let me know if higher version helped, 2015 should be high enough to support that.

Comment (warpech) [inline src/KitchenSink/DropdownPage.json.cs]: Nope, that's apparently feature of C#:

> C# 7.0 adds accessors, constructors and finalizers to the list of things that can have expression bodies.

https://blogs.msdn.microsoft.com/dotnet/2016/08/24/whats-new-in-csharp-7-0/

Comment (PatrykSzwer) [inline src/KitchenSink/DropdownPage.json.cs]: Ooou now I know.
See, in C# 6.0 came up possibility to make expression body instead of typical get. But It's not the same apparently. In C# 6.0 You could replace entire get into expression body.

(source: http://www.kunal-chowdhury.com/2014/12/csharp-6-expression-bodied-method.html#SDQhSyJJ5mlQcR3F.97)

what we encounter here is full, separate accessors support, that came up in C# 7.0, and It's not supported yet in MB tools 2015.

Comment (warpech) [inline src/KitchenSink/DropdownPage.json.cs]: Turned out to be more complex than just switching few checkboxes in TeamCity. I have started an issue to upgrade the build agent: https://github.com/Starcounter/AdminTrack/issues/283

Comment (warpech) [inline src/KitchenSink/DropdownPage.json.cs]: The build now runs with C# 7.0, but two tests are failing. @PatrykSzwer pls take a look: https://teamcity.starcounter.org/viewLog.html?buildId=24686&tab=buildResultsDiv&buildTypeId=Apps_KitchenSink_Develop

Comment (PatrykSzwer) [inline src/KitchenSink/DropdownPage.json.cs]: Done.

File: test/KitchenSink.Tests/Test/SectionArray/DropdownPageTest.cs [hunk 4]
```diff
@@ -19,6 +19,8 @@ public DropdownPageTest(Config.Browser browser) : base(browser)
         {
         }
 
+        private const string PolymerLibraryString = "Polymer JavaScript library";
+        private const string StarcounterDatabaseString = "Starcounter Database";
```
Comment (warpech) [inline test/KitchenSink.Tests/Test/SectionArray/DropdownPageTest.cs]: `String` is not needed in the variable name, since it is already in the type itself

Comment (PatrykSzwer) [inline test/KitchenSink.Tests/Test/SectionArray/DropdownPageTest.cs]: Ok, It's just some old, not really proper habit. It's fixed.
